### ISSUE TITLE
Add support for install_weak_deps property used by DNF

### ISSUE THREAD

**Issue by newatlantis** [sous-chefs/yum#193]
## Problem Statement

I would like to use the Sous Chefs' **yum** cookbook on RHEL 8 servers. The people I am working with require that we set the DNF config property `install_weak_deps` to `0` (false) in our **dnf.conf** files, so that DNF does not pull packages linked by a weak dependency relation (i.e., Recommends or Supplements flags) into the transaction. (The default value of this DNF property is `1`, or true, and we want to override that.)

## Possible Solution

When the user uses the **yum** cookbook to configure a **dnf.conf** file:

* If the user sets the node attribute `node['yum']['main']['install_weak_deps']` to `false`, then the **yum** cookbook should add the line `install_weak_deps=0` to the **dnf.conf** file.
* If the user sets the node attribute `node['yum']['main']['install_weak_deps']` to `true`, then the **yum** cookbook should add the line `install_weak_deps=1` to the **dnf.conf** file.

When the user uses the **yum** cookbook to configure a **yum.conf** file, the `node['yum']['main']['install_weak_deps']` attribute should be ignored, as it does not apply to Yum, only to DNF.

## Describe alternatives you've considered

We have forked the **yum** cookbook repo and made the changes shown below. These seem to work for our purposes. But they do this for both **yum.conf** (on RHEL 7) and **dnf.conf** (on RHEL 8) files, which seems undesirable. I think a better solution would ignore the install_weak_deps attribute for users configuring **yum.conf** files.

* In **resources/globalconfig.rb**, add this line:
  ```
  property :install_weak_deps, [true, false], description: "(DNF only) When this option is set to true and a new package is about 
  to be installed, all packages linked by a weak dependency relation (i.e., Recommends or Supplements flags) with this 
  package will be pulled into the transaction. Default is DNF's default of true."
  ```
* In **templates/main.rb**, add these lines:
  ```
  <% if @config.install_weak_deps %>
  install_weak_deps=<%= @config.install_weak_deps %>
  <% end %>
  ```

## Additional context

I don't know much about DNF. But I get the impression that lots of users will be using DNF sooner or later, and will want to use the **yum** community cookbook to configure it, as the [dnf cookbook](https://supermarket.chef.io/cookbooks/dnf) is not maintained, and DNF configuration is so similar to Yum configuration.

I took a stab at the core changes I'm looking for in my fork of the **yum** repo [HERE](https://github.com/newatlantis/yum/commit/51cc4dcdca90aee480392bb99e815492135cd658). But I'm not confident they are good enough for general use. Nor do I know how to go about writing sufficient ChefSpec unit tests for these changes. So I'm wondering if some kind soul among you would give me impossibly simple directions on the next steps I would need to take to submit a PR for this change.

Thank you for reading my issue!

**Comment by bmhughes** [comment]
I've added a couple of small changes to the PR but generally looks good and we can get it merged and released.
